version: '3.8'

services:
  app:
    build: .
    container_name: beego_app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - property_network

  db:
    image: postgres:latest
    container_name: property_db
    environment:
      POSTGRES_DB: property_listing
      POSTGRES_USER: fahimah
      POSTGRES_PASSWORD: fahimah123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - property_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - property_network

volumes:
  postgres_data:

networks:
  property_network:
    driver: bridge
# version: '3.8'

# services:
#   app:
#     build: .
#     container_name: beego_app
#     ports:
#       - "8080:8080"
#     volumes:
#       - .:/app
#     depends_on:
#       - db
#     networks:
#       - property_network
      
#   db:
#     image: postgres:latest
#     container_name: property_db
#     environment:
#       POSTGRES_DB: property_listing
#       POSTGRES_USER: fahimah
#       POSTGRES_PASSWORD: fahimah123
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - property_network

#   pgadmin:
#     image: dpage/pgadmin4:latest
#     container_name: pgadmin
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@admin.com
#       PGADMIN_DEFAULT_PASSWORD: admin
#     ports:
#       - "5050:80"
#     depends_on:
#       - db
#     networks:
#       - property_network

# volumes:
#   postgres_data:

# networks:
#   property_network:
#     driver: bridge